---
- name: Gathering Master hostIP
  command: echo {{ ansible_default_ipv4.address  }}
  register: test
- debug: msg="{{ test.stdout }}"
- name: Running KubeADM
  command: kubeadm init --pod-network-cidr 192.168.0.0/16 --apiserver-advertise-address {{ ansible_default_ipv4.address   }}  
  register: kubeadm_init_output
- debug: msg="{{ kubeadm_init_output.stdout }}"
- name: Wait for cluster to create pods
  command: sleep 120
- name: settingup kubeconfig for kubectl
  command: cp -i /etc/kubernetes/admin.conf ~/.kube/config
  #command: "{{item}}"
  #with_items:
   #       - mkdir -p $HOME/.kube
   #       - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
            #          - chown $(id -u):$(id -g) $HOME/.kube/config
#- name: change ownership
#  file: dest="$HOME/.kube/config" owner={{ ansible_user }} group={{ ansible_user}}
- name: Install calico network for k8s cluster
  command: kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml
  register: calico_check
- debug: msg="{{ calico_check.stdout   }}" 
